server:
  port: 8080 # 项目启动端口

spring:
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-c56475eaa3944b94bccd9c6f2f0797fa  # 填写阿里百炼 API Key, 改成你自己的

